const express = require('express');
const router = express.Router();
const personaCtrl = require('./controllers/personaController');
const productoCtrl = require('./controllers/productoController');
const ubicacionCtrl = require('./controllers/ubicacionController');
const ventaCtrl = require('./controllers/ventaController');
router.get('/personas', personaCtrl.getAll);
router.get('/personas/:id', personaCtrl.getById);
router.post('/personas', personaCtrl.create);
router.put('/personas/:id', personaCtrl.update);
router.delete('/personas/:id', personaCtrl.remove);
router.get('/productos', productoCtrl.getAll);
router.get('/productos/:id', productoCtrl.getById);
router.post('/productos', productoCtrl.create);
router.put('/productos/:id', productoCtrl.update);
router.delete('/productos/:id', productoCtrl.remove);
router.get('/ubicaciones', ubicacionCtrl.getAll);
router.get('/ubicaciones/:id', ubicacionCtrl.getById);
router.post('/ubicaciones', ubicacionCtrl.create);
router.put('/ubicaciones/:id', ubicacionCtrl.update);
router.delete('/ubicaciones/:id', ubicacionCtrl.remove);
router.post('/ventas', ventaCtrl.create);
router.get('/ventas/por-persona/:personaId', ventaCtrl.getByPersona);
router.get('/ventas/por-producto', ventaCtrl.countByProducto);
module.exports = router;
